trigger:
- master

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '9-mobileService'
        repository: '9-App'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'
